// server/src/models/PackagePurchase.js
const mongoose = require('mongoose');

const packagePurchaseSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    memberId: {
      type: String,
      required: true
    },
    memberName: {
      type: String,
      required: true
    },
    packageId: {
      type: String,
      required: true
    },
    packageName: {
      type: String,
      required: true
    },
    packagePrice: {
      type: Number,
      required: true
    },
    kbpPoints: {
      type: Number,
      default: 0
    },
    dailyBinaryCap: {
      type: Number,
      default: 0
    },
    selectedProduct: {
      // Legacy single-product field — kept so historical records (created
      // before multi-product tiers existed) still read back correctly.
      productId: String,
      name: String,
      category: String,
      price: Number,
      image: String
    },
    selectedProducts: [
      {
        // Current field: every tier stores here now — a 1-item array for
        // "choose 1" tiers, a 2-item array for Life Safe Elite (its spec
        // bundles both products automatically, no choice to make).
        productId: String,
        name: String,
        category: String,
        price: Number,
        image: String
      }
    ],
    paymentMethod: {
      type: String,
      default: 'CASH'
    },
    transactionId: {
      type: String,
      required: true,
      unique: true
    },
    paymentStatus: {
      // 'PENDING_VERIFICATION' is the status packagePurchase.controller.js
      // actually writes when a member submits a purchase (awaiting admin
      // approval of their UPI/gateway transaction reference) — it was
      // missing from this enum, so every member purchase submission was
      // rejected by Mongoose validation before it could ever be created.
      type: String,
      enum: ['COMPLETED', 'PENDING', 'PENDING_VERIFICATION', 'FAILED'],
      default: 'PENDING_VERIFICATION'
    },
    adminRemarks: {
      type: String
    },
    sponsorId: {
      type: String
    },
    kbp: {
      type: Number
    },
    receiptNumber: {
      type: String
    },
    paymentProof: {
      // Base64 UPI/bank-transfer screenshot the member uploads at submission
      // time. The controller has always written this field, but it was
      // missing from the schema so Mongoose silently dropped it on save —
      // the admin "View Proof" button had nothing to show.
      type: String,
      default: ''
    },
    // Distinguishes a fresh activation from a tier upgrade on an already-ACTIVE
    // member. Upgrades reuse this same pending-verification/admin-approval
    // pipeline. Per business rule, an upgrade costs the FULL price of the
    // target package (no discount for the current package's value) — so
    // `packagePrice` here always equals `targetPackagePrice`. `kbpPoints` is
    // always 0 for an upgrade: no KBP/income is generated by upgrading,
    // only the daily/weekly/monthly capping ceiling changes.
    purchaseType: {
      type: String,
      enum: ['NEW', 'UPGRADE'],
      default: 'NEW'
    },
    // True when the member picked the package's insurance plan as their
    // product — `packagePrice` is then the insurance installment they paid
    // (see constants/insurancePlans.js), while `targetPackagePrice` stays
    // the package's own price.
    isInsurance: {
      type: Boolean,
      default: false
    },
    previousPackageId: { type: String },
    previousPackageName: { type: String },
    previousPackagePrice: { type: Number },
    targetPackagePrice: { type: Number },
    activationDate: {
      type: Date,
      default: Date.now
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model('PackagePurchase', packagePurchaseSchema);